baseURL = "http://www.harddone.com/"
languageCode = "zh-CN"
title = "ColorfulDark Blog"
theme = "maupassant"
# 默认是70
summaryLength = 140
hasCJKLanguage = true
## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

googleAnalytics = "UA-139304185-1"

[taxonomies]
  category = "categories"
  tag = "tags"


[author]
  name = "ColorfulDark"

[params]
  author = "ColorfulDark"
  subtitle = "专注于Android、Java、Kotlin、移动互联网"
  keywords = "ColorfulDark,java,android,博客,python"
  description = "专注于IT互联网，包括但不限于Java、Android、Python等"

  busuanzi = true
  googleAd = "ca-pub-5294048051542592"
 

  [[params.links]]
  title = "Suntabu Blog"
  name = "Suntabu Blog"
  url = "https://www.suntabu.com/"

  [[params.links]]
  title = "巽's 部落格"
  name = "巽's 部落格"
  url = "http://www.schunlee.ml/"

 [[params.links]]
  title = "CoderZh Blog"
  name = "CoderZh Blog"
  url = "https://blog.coderzh.com/"
  

  [[params.ads]]
  title = "领取￥2000阿里云产品通用代金券"
  url = "https://promotion.aliyun.com/ntms/yunparter/invite.html?userCode=lpl70fmt"

  [[params.ads]]
  title = "领取￥2000阿里云产品通用代金券"
  url = "https://promotion.aliyun.com/ntms/yunparter/invite.html?userCode=lpl70fmt"
  img = "https://img.alicdn.com/tfs/TB17qJhXpzqK1RjSZFvXXcB7VXa-200-126.jpg"
  [[params.ads]]
  title = "领取￥2000阿里云产品通用代金券"
  url = "https://promotion.aliyun.com/ntms/yunparter/invite.html?userCode=lpl70fmt"
  img = "https://img.alicdn.com/tfs/TB1aDXhXpzqK1RjSZFvXXcB7VXa-259-194.jpg"

  [params.utteranc]
    enable = true
    repo = ""    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种

[menu]

  #[[menu.main]]
   # identifier = "books"
   #name = "新书"
   #url = "/books/"
   #weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4